### PR TITLE
[2.x] Skip Registration tests when registration feature is not enabled

### PR DESCRIPTION
**Pull request by ClaudioEyzaguirre**

### CODE REVIEW

**Comment by driesvints** [comment]
This has been attempted before and was rejected. If you don't have the functionality enabled in your app, remove the tests.

**Comment by ClaudioEyzaguirre** [comment]
@driesvints Yes, delete the tests is an option, but sometimes you need to temporarily disable user registration while early adopters (created manually) are testing your app. Then when you enable user registration again tests will be there :)

**Comment by driesvints** [comment]
You can always copy them back in.

**Comment by joelbutcher** [comment]
Or... add these conditions into the tests when they're published? The use-case you've given is extremely niche to warrant a change like this.

**Comment by driesvints** [comment]
It doesn't makes sense that end-app tests cover two different scenarios when only one scenario is the actual behavior of the app. You own these files, feel free to do with them as you please.

**Comment by driesvints** [comment]
Ah sorry @joelbutcher, I misunderstood you there.

**Comment by joelbutcher** [comment]
No problems!

**Comment by ClaudioEyzaguirre** [comment]
Thanks for your time @driesvints! As @joelbutcher said I always can modify this tests...that's why Jetstream is awesome :heart:

**Pull request closed without merging**
