### PR TITLE
Laravel mix 6 support

### PR DESCRIPTION
**Pull request by themsaid**

### CODE REVIEW

**Comment by emargareten** [comment]
@themsaid what about tailwindcss?

**Comment by themsaid** [comment]
@emargareten  what about it?

**Comment by emargareten** [comment]
@themsaid you can replace
 `'tailwindcss' => 'npm:@tailwindcss/postcss7-compat@^2.0.1',`
with
 `'tailwindcss' => '^2.0.1',`

**Comment by themsaid** [comment]
@emargareten how is that related to Laravel Mix 6? I don't understand.

**Comment by emargareten** [comment]
@themsaid The current version was only waiting for PostCSS 8

**Comment by driesvints** [comment]
@themsaid PostCSS v8 is now required in Laravel which means TailwindCSS can be bumped to the regular v2 release like @emargareten suggested.

https://github.com/laravel/laravel/pull/5505/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17

**Comment by themsaid** [comment]
Done! Thanks @emargareten for the heads up.

**Pull request merged**
