### PR TITLE
[1.x] ES linting & fixing Vue errors

### PR DESCRIPTION
**Pull request by rennokki**
Opened this PR to apply ESLint over Inertia's Vue files and eventually fix additional errors like indentation and attributes indentation (they are terrible in-line to see the diff), obsolete imports & v-bind:key errors.

Run `npm run fix` to ESLint.

Not sure if this is suitable for 1.x or should be sent directly to 2.x since it's a major BC over indentation and files.

Check the different commits as the first one ESLints the entire project and the other one adds v-bind:key to missing attributes and fixes unused components.

### CODE REVIEW

**Comment by rennokki** [comment]
As a note, perhaps it's a good idea to indent from 4 spaces to 2 as the default Vue preset does that and I have to overwrite it to fit the .editorconfig of the laravel/laravel app.

**Comment by driesvints** [comment]
@rennokki we use 4 spaces for indentation everywhere.

**Comment by driesvints** [comment]
See https://github.com/laravel/jetstream/blob/1.x/.editorconfig#L8

**Comment by rennokki** [comment]
@taylorotwell Any reason this was closed without a reason? Will it be accepted if I PR just https://github.com/laravel/jetstream/pull/297/commits/1f481017f85a732978fa40aaf66304b3e6671867 instead?

**Pull request closed without merging**
