### PR TITLE
Support RTL layout [Livewire Stack]

### PR DESCRIPTION
**Pull request by mohamedsabil83**
By adding `dir="rtl"` to the `html`, the layout will shown correctly out-of-the-box.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Hey there! Are you able to fork Jetstream and maintain these changes? I'm not sure I can maintain this styling going forward as I'm not familiar with this kind of web development.

Thanks.

**Comment by mohamedsabil83** [comment]
I always made these changes in mine. I thought it will be a good idea to be their out-of-the-box for those who use RTL direction with Tailwindcss.

**Comment by mohamedsabil83** [comment]
Hi @taylorotwell,
I can be responsible for any change required to support RTL for the Tailwind version. Hope to re-think about accepting this as it's very important for us.

**Comment by driesvints** [comment]
@mohamedsabil83 I'm sorry but we can't rely on third parties to maintain our own stuff. We've noticed enough times in the past that promises were made which couldn't be held in the end. It's probably best that you add this to your own code.

**Comment by mohamedsabil83** [comment]
It's ok

**Pull request closed without merging**
