### PR TITLE
Add Full React Support for Inertia in Jetstream

### PR DESCRIPTION
**Pull request by HichemTab-tech**
### **Description**:
This PR introduces full support for React as a stack option for Jetstream when using Inertia. While Jetstream originally supported Vue with Inertia, this update brings React into the fold, allowing developers to leverage their preferred frontend framework within the Jetstream ecosystem.

Key changes:
- New installation commands:  
  - For Vue: `php artisan jetstream:install inertia-vue --teams`  
  - For React: `php artisan jetstream:install inertia-react --teams`
- All functionality previously available with Vue (authentication, teams, profile management, etc.) is now available with React, making the switch seamless for developers who prefer React for their applications.
- Updated the tests workflow to ensure compatibility for new changes.

### **Why the Community Needs This**:
The Laravel community is diverse, with many developers opting for React in their projects. By adding official support for React, Jetstream becomes more flexible and adaptable to a wider audience. This change will not only attract more React developers to use Jetstream but will also enhance the development experience for those already familiar with React.

### **Testing the PR**:
To test this PR locally:
1. Check out the PR and rename the package in your local environment (e.g., `my/jetstream`).
2. Update your `composer.json`:
    ```json
    "repositories": [
        {
            "type": "path",
            "url": "../path/to/this-checked-out-PR"
        }
    ]
    ```
3. In your project, run the following commands:
    - `laravel new test-app`
    - `composer require my/jetstream:@dev`
    - `php artisan jetstream:install inertia-react --teams`
4. Proceed with your usual development workflow.

This addition to Jetstream is an essential enhancement that aligns with the community’s growing demand for React support within Laravel applications. Looking forward to your feedback and contribution!

### CODE REVIEW

**Comment by taylorotwell** [comment]
While I really appreciate this effort, we are focused on rebuilding our starter kits this fall using popular UI component libraries, etc.

**Comment by SergioTGSerra** [comment]
> While I really appreciate this effort, we are focused on rebuilding our starter kits this fall using popular UI component libraries, etc.

Is the development of the rebuilding being done in-house? Why not make project development open?

**Comment by Diddyy** [comment]
@HichemTab-tech Awesome PR! :)

> While I really appreciate this effort, we are focused on rebuilding our starter kits this fall using popular UI component libraries, etc.

I understand the Laravel team is focused on rebuilding the starter kits with popular UI libraries this fall—exciting stuff! Any details on how React might fit into these future plans would be great to know. Appreciate the hard work from everyone involved!

**Comment by HichemTab-tech** [comment]
@Diddyy  Thanks so much for the kind words and support, really means a lot!

@taylorotwell Hey Taylor, I hope all is well! I've resolved the latest conflicts, and I'm excited to mark this PR as ready for review again. I completely understand the direction you're taking with rebuilding the starter kits this fall—sounds like an amazing step forward for Laravel.

However, I do feel that adding React support in Jetstream could make it even more versatile for the community, given the number of developers already using React _(including me :) )._ This PR aims to fill that gap and provide a seamless experience for React users who love Laravel's ecosystem _(including me :) )_.

Would love to get your thoughts, and I hope this can still be a consideration in Jetstream's roadmap. Thanks again for all your incredible work, and for taking the time to review this!

**BTW**: If this PR is approved and everything goes well—I'd gladly offer to contribute the required parts to the documentation repository ( [jetstream](https://jetstream.laravel.com/introduction.html#available-stacks) )

**Comment by taylorotwell** [comment]
Hey there! Thanks for your work on this, but for now can you release this as a package. We are about to kick off a total revamp of our starter kit story. 🙏

**Pull request closed without merging**
