### PR TITLE
Opt-in dark mode support 

### PR DESCRIPTION
**Pull request by fotrino**
This PR introduces opt-in dark mode support to Jetstream, borrowed from @jessarcher [PR on Breeze](https://github.com/laravel/breeze/pull/209)

```
php artisan jetstream:install {stack} --dark
```

Following the previous mentioned PR, the dark mode classes will be stripped unless dark mode is enabled. 
When installing livewire stack without dark mode, the components will be published in order to strip the dark classes from them.

### Screenshots
|Light|Dark|
|-----|-----|
|register-light|register-dark|
|tos-light|tos-dark|
|privacy-policy-light|privacy-policy-light dark|
|login-light|login-dark|
|reset-password-light|reset-password-dark|
|dashboard-light|dashboard-dark|
|profile-light|profile-dark|
|confirm-password-modal-light|confirm-password-modal-dark|
|log-out-sessions-light|log-out-sessions-dark|
|delete-account-light|delete-account-dark|
|create-team-light|create-team-dark|
|edit-team-light|edit-team-dark|
|delete-team-member-light|delete-team-member-dark|
|delete-team-light|delete-team-dark|
|manage-role-light|manage-role-dark|
|api-tokens-light|api-tokens-dark|
|token-confirmation-light|token-confirmation-dark|
|token-delete-light|token-delete-dark|
|edit-token-light|edit-token-dark|
|active-user-menu-light|active-user-menu-dark|
|team-menu-light|team-menu-dark|
|focus-menu-button-light|focus-menu-button-dark|
|responsive-menu-light|responsive-menu-dark|

### Notes
- I copied the styles of inputs & buttons from Breeze PR, which will change colors from blue to indigo, happy to change back all to blue if this presents a problem.
- I used Livewire stack as a basis and then copied to Vue, while doing this I found minor inconsistencies between the stacks  which are now improved. This includes the caret icon in the user's dropdown and some minor visual differences - keep this in mind when reviewing the diff.
- I've included the fix [focus styling in this](https://github.com/laravel/jetstream/commit/e03c3a9df7e33951ea428cff493e5ffb1b8c32ac) and included the dark mode options.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for looking into this. It feels like we may want to address this issue of the black text on dark background in the logo before merging?

image

**Comment by fotrino** [comment]
Great idea! Just updated to use the dark-mode compatible logo in the repo art.

|Light|Dark|
|-----|-----|
|Screenshot 2023-01-09 at 8 23 18 AM|Screenshot 2023-01-09 at 8 23 06 AM|

**Comment by driesvints** [comment]
@fotrino thanks but looks a bit awkward. Can't we make it so it has completely white letters and no border on the icon?

**Comment by driesvints** [comment]
Might need to duplicate the SVG logo

**Comment by driesvints** [comment]
Looks much better!

**Comment by n1crack** [comment]
Nice one, I hope it releases soon .. I have tried dark mode myself before but it wasn't good enough. here is the version of mine :) 

image

**Comment by fotrino** [comment]
@driesvints the SVG are updated. Please let me know if there is anything else that needs to be looked into :)

**Comment by taylorotwell** [comment]
Thanks!

**Comment by driesvints** [comment]
Thanks @fotrino!

**Comment by ziming** [comment]
I installed jetstream months ago, this morning I did a composer update.  I never ran any jetstream:install --dark command

Tonight my sites suddenly look weird with some parts in dark and some parts in white.

It looks like this dark mode is not really opt in after all.

Screenshot attached, hope it helps. I do like dark mode a lot but perhaps it is not ready yet

CleanShot 2023-01-18 at 20 28 02

**Comment by taylorotwell** [comment]
This will have to be reverted.

**Comment by DAH-hub** [comment]
Hi there,
Please how to enable/disable dark mode programmatically ?
Thanks

**Comment by jessarcher** [comment]
> Hi there, Please how to enable/disable dark mode programmatically ? Thanks

Jetstream uses Tailwind to handle dark mode. The Tailwind docs have a section on manually toggling dark mode at https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually.

**Pull request merged**
