### PR TITLE
[1.x] Disable scrolling when modal is opened

### PR DESCRIPTION
**Pull request by octoper**
This PR disables scrolling of the page on the Y axis when a modal is opened.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Does not disable scrolling for me. Did you test this?

**Comment by bonzai** [comment]
@taylorotwell It's working fine for me. Did you recompile the CSS?

**Comment by octoper** [comment]
@taylorotwell yeah I have tested it

**Comment by andreich1980** [comment]
I tested this approach, too. Can confirm that it works - it toggles `.overflow-y-hidden` on the `body`.

I had to recompile assets to make sure the class is it the `public/app.css`, 
and hard reload the page to make sure that the browser gets the fresh `app.css`, not old one from the cache.

**Pull request closed without merging**
