### PR TITLE
Updates Tailwind on Installation to v3.0.0

### PR DESCRIPTION
**Pull request by RhysLees**
This change will update to use the latest stable versions of tailwind and tailwind plugins forms and typography

Updates @tailwindcss/forms to ^0.3.4
Updates @tailwindcss/typography to ^0.4.1
Updates tailwindcss to ^3.0.0

### CODE REVIEW

**Comment by driesvints** [comment]
Heya thanks. But this probably involves more than just version adjustments: https://tailwindcss.com/docs/upgrade-guide

**Comment by RhysLees** [comment]
> Heya thanks. But this probably involves more than just version adjustments: https://tailwindcss.com/docs/upgrade-guide

Oh, I'm actually stupid🤦‍♂️

**Comment by driesvints** [comment]
I'll mark this as in draft while you make the adjustments. Please mark it as ready when done. Thanks!

**Comment by RhysLees** [comment]
> I'll mark this as in draft while you make the adjustments. Please mark it as ready when done. Thanks!

Thanks

**Comment by RhysLees** [comment]
Wouldnt let me add to this PR so I made a new PR #919, sorry

**Pull request closed without merging**
