### PR TITLE
Fix registration test

### PR DESCRIPTION
**Pull request by vanthao03596**
Fix test fail when enable termsAndPrivacyPolicy

### CODE REVIEW

**Comment by ZeProf2Code** [comment]
See #595 #549 #593

**Comment by joelbutcher** [comment]
See https://github.com/laravel/jetstream/pull/595#issuecomment-755359750

**Comment by joelbutcher** [comment]
@taylorotwell @driesvints I'm anticipating many more of this same PR. It might be worth sticking something in the documentation or reconsidering my PR to improve this test (#595)

**Comment by driesvints** [comment]
@joelbutcher I don't believe it makes sense to put two different scenarios in end product tests. It's best to educate people rather than to bandaid this. So yeah a documentation PR could be considered.

**Comment by joelbutcher** [comment]
@driesvints of course, completely understand!

**Pull request closed without merging**
