### PR TITLE
[1.x] Changed current_team_id to big integer.

### PR DESCRIPTION
**Pull request by telkins**
(Retrying #253, which was previously attempting to merge against master.)

Please see brief conversation between myself and @driesvints : #252 

Also...I'm guessing it's best to **not** introduce foreign key constraints here...?  Personally, I would like to see them, but I'm guessing the idea would be to leave them out for now and let individual developers add them as they see fit...?

Tests passed locally.

If I'm missing anything, please let me know. 🤓

### CODE REVIEW

**Comment by driesvints** [comment]
Seems like some things went wrong here. I think it's best that you try again by branching off fresh from 1.x and recommitting.

**Comment by taylorotwell** [comment]
I can fix it.

**Comment by taylorotwell** [comment]
Hmm yeah Dries is right probably need to branch off 1.x and recommit.

**Comment by telkins** [comment]
> Seems like some things went wrong here. I think it's best that you try again by branching off fresh from 1.x and recommitting.

Yep...didn't think about that.  But, looks like @taylorotwell is on it...so I'll wait to see what shakes loose. 🤓 

Oh....looks like I should do it, anyway.  No worries....third time's the charm, right...?  😆

**Comment by telkins** [comment]
@taylorotwell or @driesvints  Hey...can you please confirm for me that you've just made this change?  I pulled the latest 1.x locally and it was already changed.  I just noticed that it's also change when viewing the source via github.  Thx.

**Comment by driesvints** [comment]
@telkins seems like Taylor has indeed fixed this already: https://github.com/laravel/jetstream/commit/1883071d771193e59ef7ed4509576e9b853dac43

Thanks for notifying us 👍

**Pull request closed without merging**
