### PR TITLE
[1.x] Added authentication guard

### PR DESCRIPTION
**Pull request by thecaliskan**
Hi;

I use this system with Nova. Two guards are required in this scenario. If there is a possibility of define, it should be. No time should be wasted to find.

Needs to be standard in config files on Laravel Official Projects.

Thanks

### CODE REVIEW

**Comment by taylorotwell** [comment]
Really should be `sanctum` as the default value.

**Comment by thecaliskan** [comment]
Default value changed `sanctum`.

**Comment by driesvints** [comment]
@thecaliskan this seems to break the test suite. Can you fix these breakages?

**Comment by thecaliskan** [comment]
@driesvints  I am fixed. Default guard should be web.

**Comment by taylorotwell** [comment]
No it shouldn't.

**Comment by thecaliskan** [comment]
Why ?

**Pull request closed without merging**
