### PR TITLE
Dark Mode v2

### PR DESCRIPTION
**Pull request by fotrino**
This PR brings back Dark Mode changes introduced in [PR 1209](https://github.com/laravel/jetstream/pull/1209) without causing issues to existing applications with Jetstream installed as it was mentioned in [Issue 1226](https://github.com/laravel/jetstream/issues/1226).

## Changes
- As suggested by @jessarcher in [this comment](https://github.com/laravel/jetstream/issues/1226#issuecomment-1396196078), the views from `views/resources` remain unchanged to avoid issues with previous installs.

-  Original files from `views/resources` have been copied to `stubs/livewire/resources/views/` to keep track of changes.

- On new installations, the following directories `stubs/livewire/resources/views/components` `stubs/livewire/resources/views/mail` will be copied to `views/vendor/jetstream/`.

- On new installations without `--dark` directive, the command `php artisan vendor:publish --tag=jetstream-views --force` was removed. Views are already published as mentioned in point above.

- The changes introduced to strip dark classes [PR 1224](https://github.com/laravel/jetstream/pull/1224), dark nav menu in [PR 1225](https://github.com/laravel/jetstream/pull/1225) have been included.

## Step to verify Issue 1226 is Fixed

1. Install new laravel app
2. Install Jetstream 2.16 `composer require laravel/jetstream`
3. Run ```php artisan jetstream:install livewire --teams```
4. Check that there are not any published jetstream views in `views/vendor/jetstream`
5. Update Jetstream to `"laravel/jetstream": "dev-dark-mode-v2"` 
6. Include the PR repo.
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/fotrino/jetstream.git"
        }
      ],
```
7. Run `composer update`

### CODE REVIEW

**Comment by jessarcher** [comment]
Thanks for tackling this one again @fotrino! I'll check it out properly once it's marked ready.

**Comment by fotrino** [comment]
Hi @jessarcher when you have a chance, take a look at the PR. Thanks!

**Comment by taylorotwell** [comment]
So does this essentially duplicate the Livewire views in Jetstream for the time being? The old legacy views and the new views that support dark mode?

**Comment by fotrino** [comment]
Yes, exactly. This will prevent any issues in previous installations without published views & new ones will work as user defines upon installation (with or without dark mode) because all the components are being published from the livewire stubs.

**Comment by taylorotwell** [comment]
@fotrino ... @jessarcher can correct me if I'm wrong, but we also batted around the idea of just tagging a Jetstream 3.0 - this would allow us to make the change without having to have the duplicated views for backwards compatibility.

**Comment by fotrino** [comment]
@taylorotwell that sounds even better! 

What do you think about moving the files from `resources/views/` to `stubs/livewire/resources/views/`? 
I think it would make it easier to determine that those components belongs to the livewire stubs.

Also, the following command `php artisan vendor:publish --tag=jetstream-views` from **[JetstreamServiceProvider](https://github.com/laravel/jetstream/blob/0c4dd31a2d9d3d3b3e8ea9a892fcd5d050be343c/src/JetstreamServiceProvider.php#L164)** could be removed, since the files would already be published in new installations & previous ones upgrading from 2.x to 3.x should have already publish their assets in order to upgrade.

**Comment by jessarcher** [comment]
I agree re: moving this to Jetstream 3.0. We'll just need to mention in the upgrade guide about publishing views prior to upgrading (if the user hasn't already).

> What do you think about moving the files from `resources/views/` to `stubs/livewire/resources/views/`? I think it would make it easier to determine that those components belongs to the livewire stubs.

I had already done some work on this in https://github.com/laravel/jetstream/pull/1118. If you take a look at [`master`](https://github.com/laravel/jetstream/tree/master) you'll notice the root-level `resources` directory is already gone.

> Also, the following command `php artisan vendor:publish --tag=jetstream-views` from **[JetstreamServiceProvider](https://github.com/laravel/jetstream/blob/0c4dd31a2d9d3d3b3e8ea9a892fcd5d050be343c/src/JetstreamServiceProvider.php#L164)** could be removed, since the files would already be published in new installations & previous ones upgrading from 2.x to 3.x should have already publish their assets in order to upgrade.

I'd already removed this in `master` as well :raised_hands:

I've just gone ahead and merged the latest `2.x` changes into `master` and fixed all of the conflicts, so it should _hopefully_ be straight-forward to apply these dark mode changes there :crossed_fingers:

The main conflict you may run into with the Inertia stack is that in 3.x the authenticated user is now shared under `auth.user` instead of just `user` (https://github.com/laravel/jetstream/pull/1073).

Thanks again for your work on this!

**Comment by taylorotwell** [comment]
Hey @fotrino! Based on @jessarcher's feedback, could you send this PR to 10.x accordingly?

**Comment by fotrino** [comment]
Hey @taylorotwell, just created a [PR](https://github.com/laravel/jetstream/pull/1234) on `master` based on the feedback from @jessarcher  😃

**Pull request closed without merging**
