### PR TITLE
Code of Conduct Feature Addition

### PR DESCRIPTION
**Pull request by blakekrone**
This PR introduces a Code of Conduct Feature to Jetstream.

Contrary to some beliefs Code of Conducts are becoming required for any application that involves user input of any kind, including avatars which could be used to present images that some would be offended by. This PR mimics the Terms And Privacy Policy Feature by creating a new codeOfConduct() Feature that can be enabled if desired.

This will introduce a new checkbox and markdown view on the registration page and is fully optional.

Minor changes were made to the term.blade.php and privacy.blade.php to fully render the objects in the browsers. Without a margin on the bottom of the page the text block doesn't fully render in an aesthetically consistent way.

### CODE REVIEW

**Comment by driesvints** [comment]
Hi there, Taylor already gave a reason on your other PR why we aren't merging this in. Sorry

**Comment by blakekrone** [comment]
I'm sorry you feel that way but how is this welcoming feature collaboration and actively encouraging pull requests by the community? This is an extremely simple request that is sorely needed in todays environment. Especially when someone has already provided the code it makes no sense to not allow it to be merged in.

**Comment by driesvints** [comment]
@blakekrone welcoming feature collaboration doesn't mean that we as maintainers are obligated to accept and merge every PR that's sent in and maintain the code indefinitely. You were give an honest and fair reasoning why we don't want to merge this. If you don't agree with that then I'm sorry you feel that way. You are, however, free to fork Jetstream and maintain your own copy if you wish or adopt the code directly in your app.

**Comment by blakekrone** [comment]
And if you will read this PR you will see that this is a feature that can be enabled or not thus making it not a requirement for all applications. I would respect and appreciate a more open collaboration dialog and allow others to provide feedback before blindly closing PRs. This is not a very welcoming procedure for someone who has his first engagement with this team.

**Comment by taylorotwell** [comment]
Hey Blake,

Sorry you feel it's not welcoming. I just don't see this as a common feature for a non-event based SaaS application such a customer management tool or an invoicing application, etc. I think it's more common in event based applications and of course Jetstream is a starting point and anyone could add that to their application if they want. Or they could simply use the existing "Terms of Service" feature that Jetstream already offers.

Would echo Dries' comment that at the end of the day I'm the maintainer of this repository and I just know that regardless of any other discussion that takes place I don't feel this feature is going to fit most use cases that Jetstream is used for. And, I maintain this repository out of my free time so I'm not going to include this feature.

👍

**Pull request closed without merging**
