### PR TITLE
[2.x] Tailwind 2

### PR DESCRIPTION
**Pull request by themsaid**
This PR upgrades Jetstream stacks to use Tailwindcss v2

### CODE REVIEW

**Comment by srdante** [comment]
I think you forgot to remove the @tailwindcss/ui plugin for the livewire stack, which is no longer needed in TailwindCSS 2.

src/Console/InstallCommand.php - Line 117

**Comment by themsaid** [comment]
@srdante removed. thanks

**Comment by bonzai** [comment]
I would create a new `Checkbox` component (like `Input`), because there is a lot of duplicated code.

**Comment by taylorotwell** [comment]
I agree it may be nice to make a Checkbox component now. @themsaid can you look into that?

**Comment by NeptuneDesign** [comment]
Why not use the `Input` component, for example : `<x-input type="checkbox" />`

**Comment by themsaid** [comment]
Added a new checkbox component to the inertia and livewire stacks

**Comment by richardkeep** [comment]
@themsaid  The Select input too is very necessary

**Comment by themsaid** [comment]
@richardkeep The purpose of this PR is to upgrade to Tailwind2. Feel free to open PRs with other features/refactoring.

**Comment by mubashariqbal** [comment]
I believe the checkbox/input are missing the "border" utility class.  As the code stands the border color applied has no affect.

https://play.tailwindcss.com/Q0vDJ0FloH

**Comment by mubashariqbal** [comment]
Thanks, updated but adding had no affect: https://play.tailwindcss.com/J80flR1s2q

**Comment by NeptuneDesign** [comment]
https://play.tailwindcss.com/bmMQ6sUz8H

**Comment by bonzai** [comment]
You forgot about the `type` attribute (it's required):

Zrzut ekranu 2020-11-26 o 15 14 53

**Comment by mubashariqbal** [comment]
I see, got it, thanks!

**Pull request merged**
